### ISSUE TITLE
Activity detailpage

### ISSUE THREAD

**Issue by DaanH123** [BasGarretsen/picobelloBVITsolutions#15]
When someone clicks on a activity in the #12 they go to a detail page where the can see al the detail of the activity such as:

. list op people who signed up for the activity,
· activiteitnaam (M),
· locatie(M),
· inclusief eten ja nee?(M),
· omschrijving(M),
· begin tijd(M),
· eindtijd(M),
· kosten(M),
· maximaal aantal deelnemers (S),
· minimaal aantal deelnemers (S),
· en een afbeelding(S),
· benodigdheden(C)

**Comment by JuliusDeBoer** [comment]
Imagine public repo

**Comment by JuliusDeBoer** [comment]
![Image](https://github.com/user-attachments/assets/114aa8bc-8928-4285-9c0e-9174ea0048db)

**Comment by JuliusDeBoer** [comment]
![Image](https://github.com/user-attachments/assets/31f1d46d-2692-47cf-962c-3289be042e20)
